services:
  db:
      image: postgres:alpine
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    ports:
      - '4000:4000'
volumes:
  postgres_data: